version: 1.2

workflows:
  - name: wdl-mothur
    subclass: WDL
    primaryDescriptorPath: /mothur.wdl
    readMePath: /README.md
    authors:
      - name: Jesse Wolf
        email: jesse@dnastack.com
        orcid: 0000-0003-0773-4456
